package net.hiddenpass.hiddenpass.enumerations;

public enum EBenefits {
    FIFTEEN_PASSWORD,
    FIFTY_PASSWORD,
    UNLIMITED_PASSWORD,

    TEN_NOTES,
    TWENTY_NOTES,
    UNLIMITED_NOTES,

    UNLIMITED_GENERATOR_PASSWORD,

    SUPPORT,
    SECURITY_BREACH_ALERTS,
    WEAK_PASSWORD_ANALYSIS,
    TWO_FACTOR_AUTH_SUPPORT,
    CLOUD_BACKUP
}
